# Generated by Django 6.0.5 on 2026-05-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
