# Generated by Django 6.0.5 on 2026-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('politics', 'Politics'), ('sports', 'Sports'), ('culture', 'Culture'), ('government', 'Government'), ('current_affairs', 'Current Affairs')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'difficulty'], name='questions_q_categor_696e26_idx'),
        ),
    ]
