# Generated by Django 6.0.5 on 2026-05-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_userapikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApiKey',
        ),
    ]
