# Generated by Django 6.0.5 on 2026-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
