# Generated by Django 6.0.5 on 2026-05-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='prefix',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
