# Generated by Django 6.0.5 on 2026-05-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_alter_userapikey_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
