# Generated by Django 6.0.5 on 2026-05-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0003_alter_userapikey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapikey',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='id',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='prefix',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
