# Generated by Django 6.0.5 on 2026-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0004_remove_userapikey_created_at_alter_userapikey_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
