# Generated by Django 6.0.5 on 2026-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0005_userapikey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
