# Generated by Django 6.0.5 on 2026-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0008_alter_userapikey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='id',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
